### ISSUE TITLE
Why was this released to the public!?

### ISSUE THREAD

**Issue by davewthompson** [ariercole/Cambridge_COVID-19_ICU#1]
You need to make it clear this is not peer reviewed, and appears to have been irresponsibly released to the general public and the media rather than sent to the decision-makers who understand the information inside it and the constraints it has been published under.

**Comment by davewthompson** [comment]
I fully agree with the science - I am just questioning whether or not releasing this to the public is the correct course of action.

**Comment by ariercole** [comment]
It has been sent to the decision makers as well. The science is urgent and needs to also be disseminated to intensive care units.

BW
Ari

**Comment by ariercole** [comment]
Furthermore it has been uploaded to medRxiv but this takes 3-4 days each revision. We will add something to the README.md and m’script to make this clearer.

**Comment by davewthompson** [comment]
Understood. Let us hope the public understand!

**Comment by EmmaRocheteau** [comment]
Can confirm both have been edited. Thanks for your comments
