### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '../figs'

### ISSUE THREAD

**Issue by anonym0305** [ariercole/Cambridge_COVID-19_ICU#2]
**Hi Emma: Thanks for the great work. However, I'm seeing an error, as below. Any suggestions ?
Also, I'm assuming that since the code has been distributed under MIT licence it is available for academics to reference, modify and use for further research.** 
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-4-b8437125d74a> in <module>
      1 save_dir = os.path.join(os.pardir, 'figs')
      2 if not os.path.exists(save_dir):
----> 3     os.makedirs(save_dir)

/srv/conda/envs/notebook/lib/python3.7/os.py in makedirs(name, mode, exist_ok)
    219             return
    220     try:
--> 221         mkdir(name, mode)
    222     except OSError:
    223         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [Errno 13] Permission denied: '../figs'

**Comment by jacobdeasy** [comment]
Hi! Thanks for the feedback.
This permission error may be due to your operating system.
Try using the 2nd answer on [this stackoverflow answer](https://stackoverflow.com/questions/12468022/python-fileexists-error-when-making-directory).

**Comment by anonym0305** [comment]
Guess per your suggestion, my script should be: 
save_dir = os.path.join(os.pardir, 'figs')
if not os.path.exists(save_dir):
    os.makedirs(save_dir**, exist_ok=True**)

But looks like the error's still there. Any suggestions ?

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-3-087db905bc12> in <module>
      1 save_dir = os.path.join(os.pardir, 'figs')
      2 if not os.path.exists(save_dir):
----> 3     os.makedirs(save_dir, exist_ok=True)

/srv/conda/envs/notebook/lib/python3.7/os.py in makedirs(name, mode, exist_ok)
    219             return
    220     try:
--> 221         mkdir(name, mode)
    222     except OSError:
    223         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [Errno 13] Permission denied: '../figs'

**Comment by jacobdeasy** [comment]
If you don't have permission to make a directory in the parent folder, you can remove `os.pardir`.
Alternatively, if you are happy to have the figures output to the current folder, you can remove both lines and simply have `save_dir = ''`.

**Comment by anonym0305** [comment]
Hi Jacob: Thanks for helping me out with this. Option 1 worked. But I'm now
stuck on a later line of code, as below. Everything works well before this
part.


---------------------------------------------------------------------------FileNotFoundError
                        Traceback (most recent call
last)<ipython-input-7-68e0e86a7c55> in <module>----> 1 X, X_pred,
cum_cases, regions, dates = load_data()
~/graphs.py in load_data()     28      29 def load_data():---> 30
daily_cases = pd.read_csv(os.path.join(os.pardir, 'data', 'model',
'uptodate_cases.csv'))     31      32     regions =
daily_cases['region']
/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/parsers.py
in parser_f(filepath_or_buffer, sep, delimiter, header, names,
index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine,
converters, true_values, false_values, skipinitialspace, skiprows,
skipfooter, nrows, na_values, keep_default_na, na_filter, verbose,
skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col,
date_parser, dayfirst, cache_dates, iterator, chunksize, compression,
thousands, decimal, lineterminator, quotechar, quoting, doublequote,
escapechar, comment, encoding, dialect, error_bad_lines,
warn_bad_lines, delim_whitespace, low_memory, memory_map,
float_precision)    674         )    675 --> 676         return
_read(filepath_or_buffer, kwds)    677     678     parser_f.__name__ =
name
/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/parsers.py
in _read(filepath_or_buffer, kwds)    446     447     # Create the
parser.--> 448     parser = TextFileReader(fp_or_buf, **kwds)    449
  450     if chunksize or iterator:
/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/parsers.py
in __init__(self, f, engine, **kwds)    878
self.options["has_index_names"] = kwds["has_index_names"]    879 -->
880         self._make_engine(self.engine)    881     882     def
close(self):
/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/parsers.py
in _make_engine(self, engine)   1112     def _make_engine(self,
engine="c"):   1113         if engine == "c":-> 1114
self._engine = CParserWrapper(self.f, **self.options)   1115
else:   1116             if engine == "python":
/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/parsers.py
in __init__(self, src, **kwds)   1889         kwds["usecols"] =
self.usecols   1890 -> 1891         self._reader =
parsers.TextReader(src, **kwds)   1892         self.unnamed_cols =
self._reader.unnamed_cols   1893
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()
pandas/_libs/parsers.pyx in
pandas._libs.parsers.TextReader._setup_parser_source()
FileNotFoundError: [Errno 2] File ../data/model/uptodate_cases.csv
does not exist: '../data/model/uptodate_cases.csv'




~Sash

**Comment by jacobdeasy** [comment]
This is because the development repo has a slightly different structure to this repo, this will be amended in future patches.
Replace:
`daily_cases = pd.read_csv(os.path.join(os.pardir, 'data', 'model', 'uptodate_cases.csv'))`
With:
`daily_cases = pd.read_csv(os.path.join('data', 'model', 'uptodate_cases.csv'))`

**Comment by EmmaRocheteau** [comment]
regarding your first question about the licence, yes do what you like with the code!

**Comment by anonym0305** [comment]
Great thanks, Emma. Hi to y'all from Canada!

@Jacob: So, I tried


*def load_data():            daily_cases = pd.read_csv(os.path.join('data',
'model', 'uptodate_cases.csv'))*
and then

*X, X_pred, cum_cases, regions, dates = load_data()*

But am still getting an error. Surely, I'm missing something but don't know
what! Your guidance is much appreciated.

---------------------------------------------------------------------------TypeError
                                Traceback (most recent call
last)<ipython-input-16-68e0e86a7c55> in <module>----> 1 X, X_pred,
cum_cases, regions, dates = load_data()
TypeError: cannot unpack non-iterable NoneType object




~Sash

**Comment by anonym0305** [comment]
Hi Jacob - I'm still getting this error. TypeError: cannot unpack non-iterable NoneType object
Any suggestions on how to proceed ? Thanks.

**Comment by EmmaRocheteau** [comment]
Have you checked that daily cases is loading correctly?
